hard_tabs = true
newline_style = "Unix"
use_field_init_shorthand = true

# Unstable settings
# group_imports = "one" # https://github.com/rust-lang/rustfmt/issues/5083
# reorder_impl_items = true
# imports_granularity='Crate'
