[workspace]
resolver = "2"
members = [
    "client",
    "server",
    "shared",
    "shared/derive",
    "shared/serde",
    "shared/serde/derive",
    "socket/client",
    "socket/server",
    "socket/shared",
    "test",
]
default-members = [
    "client",
    "server",
    "shared",
    "shared/derive",
    "shared/serde",
    "shared/serde/derive",
    "socket/client",
    "socket/server",
    "socket/shared",
]

[profile.release]
opt-level = 's'
lto = true
