[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
copyleft = "deny"
allow-osi-fsf-free = "either"

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
